### ISSUE TITLE
ripser options (format, dim, threshold, modulus, …)

### ISSUE THREAD

**Issue by mattearnshaw** [rrrlw/ripserr#1]
do you have any plan to support these options via your interface?

**Comment by rrrlw** [comment]
Absolutely; unfortunately, due to other commitments, this will likely not happen until June/July 2018. :(

**Comment by paigero** [comment]
Thanks so much for creating ripserr. I need to compute persistent homologies of dimension 2 and higher. How can I get ripserr to do this?

**Comment by rrrlw** [comment]
Yes, you are correct, this is definitely a bug in ripserr. Thank you for pointing it out! I will try to get it fixed as soon as possible.

**Comment by paigero** [comment]
Dear Raoul,

Thank you so much in advance,

Rob Paige

**Comment by rrrlw** [comment]
@mattearnshaw The dim and threshold options have been implemented in the TDAstats R package (https://github.com/rrrlw/TDAstats) that is intended to replace the ripserr package. The modulus option should be added soon as well. I am unsure how many formats I will support apart from point cloud; is there a particular format that would be useful in your work?

**Comment by rrrlw** [comment]
@paigero The TDAstats R package (https://github.com/rrrlw/TDAstats) is intended to replace the ripserr R package, as it has more functionality (visualization and inference, in addition to calculation of persistent homology). The `TDAstats::calculate_homology` function is used to calculate persistent homology (with the C++ Ripser library doing the work behind the R code); it has a parameter named dim, which represents the maximum dimension for which to calculate persistent homology. Thus, the function call `calculate_homology(point.cloud, dim = 2)` should do the trick. Please let me know if this works for you.

**Comment by mattearnshaw** [comment]
@rrrlw thanks for the heads up! point cloud alone works for me.

**Comment by paigero** [comment]
Raoul,

The point cloud format is most useful in my work.

Thanks much in advance for your hard work,

Rob

**Comment by paigero** [comment]
Raoul,

Great!! Thank you so much.

Rob

**Comment by rrrlw** [comment]
Thank you, @paigero, appreciate the kind words. Please let me know if there are any issues with TDA stats at https://github.com/rrrlw/TDAstats.

**Comment by rrrlw** [comment]
@mattearnshaw apologies, but upon a closer look, it appears that the modulus option will not be supported as it required the USE_COEFFICIENTS flag during C++ compilation of Ripser (which is not used in TDAstats). See https://github.com/Ripser/ripser for details. Thank you for using TDAstats, let me know if there are any issues at https://github.com/rrrlw/TDAstats/issues!
