### ISSUE TITLE
cubical ripser for image and volume data

### ISSUE THREAD

**Issue by corybrunson** [rrrlw/ripserr#2]
See [the preprint by Kaji, Sudo, and Ahara](https://arxiv.org/abs/2005.12692). While the interface is in Python, the source code is in C++. Rather than several single-engine porting packages, it may be good to port several related C++ engines to R in one package, and this cubical Ripser looks like a suitable candidate!

**Comment by rrrlw** [comment]
2-dim and 4-dim calculations for cubical ripser have been added in `cubical` branch; had some weird errors w/ 3-dim, will try again soon (N.B. `cubical` function takes either 2-dim or 4-dim `array` object w/ `numeric` elements and doesn't have parameter error-checking or anything yet)

Thanks for the issue/suggestion!

**Comment by rrrlw** [comment]
added cubical 3-dim in `cubical` branch at 97e768d

**Comment by rrrlw** [comment]
N.B. still need to add error-checking, size limits, etc. but basic functionality is there in `ripserr::cubical`

**Comment by rrrlw** [comment]
ripserr v0.1.1 went through all 12 checks on [CRAN](https://CRAN.R-project.org/package=ripserr) w/o issues - ports CubicalRipser in the `cubical` function
